//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperLessOffice_ir_WebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PaperLessOffice_irEntities : DbContext
    {
        public PaperLessOffice_irEntities()
            : base("name=PaperLessOffice_irEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ref_JobType> Ref_JobType { get; set; }
        public virtual DbSet<Ref_wfStatus> Ref_wfStatus { get; set; }
        public virtual DbSet<Tab_jobs> Tab_jobs { get; set; }
        public virtual DbSet<tab_Options> tab_Options { get; set; }
        public virtual DbSet<Tab_Process> Tab_Process { get; set; }
        public virtual DbSet<Tab_Template> Tab_Template { get; set; }
        public virtual DbSet<Tab_UserJob> Tab_UserJob { get; set; }
        public virtual DbSet<Tab_userProcess> Tab_userProcess { get; set; }
        public virtual DbSet<Tab_users> Tab_users { get; set; }
        public virtual DbSet<Tab_wfTransactions> Tab_wfTransactions { get; set; }
        public virtual DbSet<Tab_workflow> Tab_workflow { get; set; }
        public virtual DbSet<tab_Orgmapp> tab_Orgmapp { get; set; }
        public virtual DbSet<tab_Orgstruct> tab_Orgstruct { get; set; }
    
        public virtual ObjectResult<EmpOptions_Result> EmpOptions(Nullable<long> procid, Nullable<long> jobid)
        {
            var procidParameter = procid.HasValue ?
                new ObjectParameter("procid", procid) :
                new ObjectParameter("procid", typeof(long));
    
            var jobidParameter = jobid.HasValue ?
                new ObjectParameter("jobid", jobid) :
                new ObjectParameter("jobid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EmpOptions_Result>("EmpOptions", procidParameter, jobidParameter);
        }
    
        public virtual ObjectResult<Get_WfHistory_Result> Get_WfHistory(Nullable<long> wfid)
        {
            var wfidParameter = wfid.HasValue ?
                new ObjectParameter("wfid", wfid) :
                new ObjectParameter("wfid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_WfHistory_Result>("Get_WfHistory", wfidParameter);
        }
    
        public virtual ObjectResult<GetOptionList_Result> GetOptionList(Nullable<long> procid, Nullable<long> jobid, Nullable<long> wfid, Nullable<long> userid, Nullable<long> wfStatusCode, Nullable<long> lastJobId, Nullable<long> lastOptid)
        {
            var procidParameter = procid.HasValue ?
                new ObjectParameter("procid", procid) :
                new ObjectParameter("procid", typeof(long));
    
            var jobidParameter = jobid.HasValue ?
                new ObjectParameter("jobid", jobid) :
                new ObjectParameter("jobid", typeof(long));
    
            var wfidParameter = wfid.HasValue ?
                new ObjectParameter("wfid", wfid) :
                new ObjectParameter("wfid", typeof(long));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            var wfStatusCodeParameter = wfStatusCode.HasValue ?
                new ObjectParameter("wfStatusCode", wfStatusCode) :
                new ObjectParameter("wfStatusCode", typeof(long));
    
            var lastJobIdParameter = lastJobId.HasValue ?
                new ObjectParameter("lastJobId", lastJobId) :
                new ObjectParameter("lastJobId", typeof(long));
    
            var lastOptidParameter = lastOptid.HasValue ?
                new ObjectParameter("LastOptid", lastOptid) :
                new ObjectParameter("LastOptid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOptionList_Result>("GetOptionList", procidParameter, jobidParameter, wfidParameter, useridParameter, wfStatusCodeParameter, lastJobIdParameter, lastOptidParameter);
        }
    
        public virtual ObjectResult<Pro_ExecuteWf_Result> Pro_ExecuteWf(Nullable<long> uid, Nullable<long> procid, Nullable<long> wfid, string doc, string note, Nullable<long> optionid, Nullable<long> sendto)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(long));
    
            var procidParameter = procid.HasValue ?
                new ObjectParameter("procid", procid) :
                new ObjectParameter("procid", typeof(long));
    
            var wfidParameter = wfid.HasValue ?
                new ObjectParameter("wfid", wfid) :
                new ObjectParameter("wfid", typeof(long));
    
            var docParameter = doc != null ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(string));
    
            var noteParameter = note != null ?
                new ObjectParameter("note", note) :
                new ObjectParameter("note", typeof(string));
    
            var optionidParameter = optionid.HasValue ?
                new ObjectParameter("optionid", optionid) :
                new ObjectParameter("optionid", typeof(long));
    
            var sendtoParameter = sendto.HasValue ?
                new ObjectParameter("sendto", sendto) :
                new ObjectParameter("sendto", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_ExecuteWf_Result>("Pro_ExecuteWf", uidParameter, procidParameter, wfidParameter, docParameter, noteParameter, optionidParameter, sendtoParameter);
        }
    
        public virtual ObjectResult<Pro_GetFinishedProc_Result> Pro_GetFinishedProc(Nullable<long> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_GetFinishedProc_Result>("Pro_GetFinishedProc", useridParameter);
        }
    
        public virtual ObjectResult<Pro_GetLateWf_Result> Pro_GetLateWf(Nullable<long> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_GetLateWf_Result>("Pro_GetLateWf", useridParameter);
        }
    
        public virtual ObjectResult<Pro_GetMyInprogressProc_Result> Pro_GetMyInprogressProc(Nullable<long> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_GetMyInprogressProc_Result>("Pro_GetMyInprogressProc", useridParameter);
        }

        public virtual ObjectResult<ProGetMyJobResponse> Pro_GetMyJob(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProGetMyJobResponse>("Pro_GetMyJob", useridParameter);
        }
    }
}
