//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperLessOffice_ir_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Process
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tab_Process()
        {
            this.tab_Options = new HashSet<tab_Options>();
            this.Tab_Template = new HashSet<Tab_Template>();
            this.Tab_userProcess = new HashSet<Tab_userProcess>();
            this.Tab_workflow = new HashSet<Tab_workflow>();
        }
    
        public long procid { get; set; }
        public string procname { get; set; }
        public Nullable<bool> procactive { get; set; }
        public Nullable<long> startjob { get; set; }
        public Nullable<int> ProcType { get; set; }
        public Nullable<long> startjobtime { get; set; }
        public Nullable<long> procwu { get; set; }
        public Nullable<bool> ToBeArchived { get; set; }
        public string helplink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tab_Options> tab_Options { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tab_Template> Tab_Template { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tab_userProcess> Tab_userProcess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tab_workflow> Tab_workflow { get; set; }
    }
}
