//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperLessOffice_ir_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_UserJob
    {
        public long ujid { get; set; }
        public long userid { get; set; }
        public long jobid { get; set; }
        public Nullable<bool> ujActive { get; set; }
        public Nullable<bool> onlyLate { get; set; }
    
        public virtual Tab_jobs Tab_jobs { get; set; }
        public virtual Tab_users Tab_users { get; set; }
    }
}
