//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperLessOffice_ir_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_wfTransactions
    {
        public long wftid { get; set; }
        public Nullable<long> wfid { get; set; }
        public Nullable<System.DateTime> transdate { get; set; }
        public Nullable<long> optionselected { get; set; }
        public string note { get; set; }
        public Nullable<long> userid { get; set; }
        public string VerDoc { get; set; }
    
        public virtual tab_Options tab_Options { get; set; }
        public virtual Tab_users Tab_users { get; set; }
        public virtual Tab_workflow Tab_workflow { get; set; }
    }
}
