//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperLessOffice_ir_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_workflow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tab_workflow()
        {
            this.Tab_wfTransactions = new HashSet<Tab_wfTransactions>();
        }
    
        public long wfid { get; set; }
        public Nullable<long> userid { get; set; }
        public Nullable<long> procid { get; set; }
        public Nullable<long> template_id { get; set; }
        public Nullable<long> InitialJob { get; set; }
        public string doc { get; set; }
        public Nullable<int> wfstatusCode { get; set; }
        public Nullable<long> wfcurrentjob { get; set; }
        public Nullable<long> lastOption { get; set; }
        public Nullable<bool> isopen { get; set; }
        public Nullable<System.DateTime> timeJobStart { get; set; }
        public Nullable<System.DateTime> alarmtime { get; set; }
        public Nullable<bool> viewed { get; set; }
        public Nullable<System.DateTime> processStartTime { get; set; }
        public Nullable<System.DateTime> processEndTime { get; set; }
        public Nullable<System.Guid> tokenUID { get; set; }
    
        public virtual Ref_wfStatus Ref_wfStatus { get; set; }
        public virtual Tab_jobs Tab_jobs { get; set; }
        public virtual tab_Options tab_Options { get; set; }
        public virtual Tab_Process Tab_Process { get; set; }
        public virtual Tab_Template Tab_Template { get; set; }
        public virtual Tab_users Tab_users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tab_wfTransactions> Tab_wfTransactions { get; set; }
    }
}
