//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperLessOffice_ir_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tab_users()
        {
            this.Tab_UserJob = new HashSet<Tab_UserJob>();
            this.Tab_userProcess = new HashSet<Tab_userProcess>();
            this.Tab_wfTransactions = new HashSet<Tab_wfTransactions>();
            this.Tab_workflow = new HashSet<Tab_workflow>();
        }
    
        public long userid { get; set; }
        public string username { get; set; }
        public string pwd { get; set; }
        public string fullname { get; set; }
        public Nullable<long> wu { get; set; }
        public Nullable<int> position { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<long> inbox { get; set; }
        public Nullable<long> reportTo { get; set; }
        public Nullable<long> viewWU { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public Nullable<decimal> cid { get; set; }
        public string location { get; set; }
        public Nullable<int> fpid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tab_UserJob> Tab_UserJob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tab_userProcess> Tab_userProcess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tab_wfTransactions> Tab_wfTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tab_workflow> Tab_workflow { get; set; }
    }
}
