//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperLessOffice_ir_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Template
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tab_Template()
        {
            this.Tab_workflow = new HashSet<Tab_workflow>();
        }
    
        public long template_id { get; set; }
        public Nullable<long> Procid { get; set; }
        public string tempname { get; set; }
        public string tempURL { get; set; }
        public string temppath { get; set; }
        public Nullable<bool> tempactive { get; set; }
        public string version { get; set; }
    
        public virtual Tab_Process Tab_Process { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tab_workflow> Tab_workflow { get; set; }
    }
}
