//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperLessOffice_ir_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_Options
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tab_Options()
        {
            this.Tab_wfTransactions = new HashSet<Tab_wfTransactions>();
            this.Tab_workflow = new HashSet<Tab_workflow>();
        }
    
        public long optionid { get; set; }
        public string OptName { get; set; }
        public Nullable<int> Option_Type { get; set; }
        public Nullable<int> Query_id { get; set; }
        public string Procedure_name { get; set; }
        public string Procedure_Param { get; set; }
        public Nullable<long> pjid { get; set; }
        public Nullable<long> procid { get; set; }
        public Nullable<long> jobid { get; set; }
        public Nullable<long> nextjob { get; set; }
        public Nullable<bool> optactive { get; set; }
        public Nullable<int> nxtstatus { get; set; }
        public Nullable<long> nxtmaxtime { get; set; }
        public Nullable<long> WCF_id { get; set; }
        public Nullable<long> WCF_method { get; set; }
        public string WCF_Param { get; set; }
        public string CallFunction { get; set; }
        public string FunctionParamList { get; set; }
        public Nullable<bool> AutomaticOpt { get; set; }
    
        public virtual Ref_wfStatus Ref_wfStatus { get; set; }
        public virtual Tab_jobs Tab_jobs { get; set; }
        public virtual Tab_jobs Tab_jobs1 { get; set; }
        public virtual Tab_Process Tab_Process { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tab_wfTransactions> Tab_wfTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tab_workflow> Tab_workflow { get; set; }
    }
}
