//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperLessOffice_ir_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_Orgstruct
    {
        public decimal unit_code { get; set; }
        public Nullable<decimal> parent_unit { get; set; }
        public string unit_name { get; set; }
        public Nullable<decimal> unit_level { get; set; }
        public Nullable<decimal> unit_type { get; set; }
        public Nullable<decimal> unit_discode { get; set; }
        public Nullable<int> tender_master { get; set; }
    }
}
